### ISSUE TITLE
Grid generation stopping at the right condition

### ISSUE THREAD

**Issue by MonicaBrandeis** [spatialdev/osmquality#20]
Currently, we found that the grid stop condition is not as precise as we thought it is. We would like to investigate why and fix it. 

Test 1: Default condition - 90% of the grid has less than 10 counts
Test 2: Custom condition - 95% of the grid has less than 5 counts

Test case - SEA

**Comment by MonicaBrandeis** [comment]
The counts based on our test is off by two variables in https://github.com/spatialdev/osmquality/blob/master/src/mqm/mqm_tool.py

```total_count_within_count_num``` has higher counts that is should be 
```total_grids```should just gather the counts from 2 power levels of K-D tree

Still working on debugging and enhancement

**Comment by MonicaBrandeis** [comment]
```total_count_within_count_num``` will count two more "bars" than what's defined, so for example, if we use the default, it will count # of grids contains 10 + # of grid contains 11 as extra counting

**Comment by danielduhh** [comment]
Fixed by #22
